resources:
  - url: http://127.0.0.1:5004/platinum-weather-card.js
    type: module
views:
  - cards:
      - type: custom:platinum-weather-card
        name: Platinum Weather Card Development
        entity: sun.sun
        test_gui: true
