name: 'Build'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          rm -rf /home/runner/work/platinum-weather-card/platinum-weather-card/node_modules
          npm install
          "npm run lint && npm run rollup -c rollup.config.js
          ls -R /home/runner/work/platinum-weather-card/platinum-weather-card/dist
