name: 'Sync Develop to Master'

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Sync Develop to Master
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Opening pull request
        id: pull
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: 'develop'
          TO_BRANCH: 'master'
      - name: Label the pull request to ignore for release note generation
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: automerge
          repo: ${{ github.repository }}
          number: ${{ steps.pull.outputs.PULL_REQUEST_NUMBER }}
